package com.troquim_bot.ai.intent;

public enum IntentType {
    SAUDACAO,
    AGRADECIMENTO,
    DESPEDIDA,
    HUMANO,
    ORCAMENTO,
    AGENDAMENTO,
    CONSULTAR_AGENDAMENTO,
    NOVO_AGENDAMENTO,
    CONSULTAR_NOME,
    LEMBRAR_CLIENTE,
    CONSULTAR_SERVICOS,
    DESCONHECIDO
}
