package com.troquim_bot.ai.intent;

public enum IntentType {
    LEMBRAR_CLIENTE,
    SAUDACAO,
    AGRADECIMENTO,
    DESPEDIDA,
    HUMANO,
    ORCAMENTO,
    AGENDAMENTO,
    CONSULTAR_AGENDAMENTO,
    CONSULTAR_DIA_AGENDADO,
    CONSULTAR_HORARIO_AGENDADO,
    CONSULTAR_SERVICO_AGENDADO,
    CONSULTAR_NOME,
    CONSULTAR_SERVICOS,
    CONSULTAR_HORARIOS,
    CONSULTAR_ENDERECO,
    CONSULTAR_QUEM_SOU,
    NOVO_AGENDAMENTO,
    DESCONHECIDO
}
