package com.troquim_bot.application.intent;

public enum IntentType {
    GREETING,
    BOOK_APPOINTMENT,
    CANCEL_APPOINTMENT,
    RESCHEDULE_APPOINTMENT,
    CHECK_AVAILABILITY,
    ASK_SERVICES,
    ASK_HOURS,
    ASK_LOCATION,
    ASK_WHO_ARE_YOU,
    HUMAN_ATTENDANT,
    AGRADECIMENTO,
    DESPEDIDA,
    LEMBRAR_CLIENTE,
    CONSULTAR_AGENDAMENTO,
    CONSULTAR_DIA_AGENDADO,
    CONSULTAR_HORARIO_AGENDADO,
    CONSULTAR_SERVICO_AGENDADO,
    CONSULTAR_NOME,
    UNKNOWN
}
