'use client'

import { useEffect, useState } from 'react'
type Service={id:string;name:string}
type Professional={id:string;name:string;phone:string;specialties:string[];enabledServiceIds:string[];status:string}

export default function EquipePage(){
 const [items,setItems]=useState<Professional[]>([]);const [services,setServices]=useState<Service[]>([]);const [editing,setEditing]=useState<Professional|null>(null);const [creating,setCreating]=useState(false);const [error,setError]=useState('')
 async function load(){const [p,s]=await Promise.all([fetch('/api/app/professionals'),fetch('/api/app/services')]);if(p.ok)setItems(await p.json());if(s.ok)setServices((await s.json()).filter((x:Service & {status:string})=>x.status==='ATIVO'))}
 useEffect(()=>{void load()},[])
 async function status(x:Professional){const r=await fetch(`/api/app/professionals/${x.id}/status`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({active:x.status!=='ATIVO'})});if(!r.ok){setError('Não foi possível alterar o profissional.');return}await load()}
 return <div className="page"><div className="sectionHead"><div><div className="eyebrow">Equipe</div><h1 className="title">Profissionais</h1></div><button className="touchButton primary" onClick={()=>setCreating(true)}>+ Novo</button></div>{error&&<div className="inlineError">{error}</div>}<div className="appointmentCards">{items.map(x=><article className="appointmentCard" key={x.id}><div className="appointmentTop"><div><strong>{x.name}</strong><div className="appointmentMeta">{x.phone}<br/>{x.enabledServiceIds.length} serviço(s)</div></div><span className="pill">{x.status}</span></div><div className="actionRow" style={{marginTop:12}}><button className="touchButton secondary" onClick={()=>setEditing(x)}>Editar</button><button className="touchButton secondary" onClick={()=>status(x)}>{x.status==='ATIVO'?'Pausar':'Ativar'}</button></div></article>)}</div>{(editing||creating)&&<ProfessionalSheet item={editing} services={services} onClose={()=>{setEditing(null);setCreating(false)}} onSaved={async()=>{setEditing(null);setCreating(false);await load()}}/>}</div>
}
function ProfessionalSheet({item,services,onClose,onSaved}:{item:Professional|null;services:Service[];onClose:()=>void;onSaved:()=>void}){const [name,setName]=useState(item?.name??'');const [phone,setPhone]=useState(item?.phone??'');const [enabled,setEnabled]=useState<string[]>(item?.enabledServiceIds??[]);const [error,setError]=useState('');async function save(){const url=item?`/api/app/professionals/${item.id}`:'/api/app/professionals';const r=await fetch(url,{method:item?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,phone,specialties:item?.specialties??[],enabledServiceIds:enabled})});const b=await r.json().catch(()=>({}));if(!r.ok){setError(b.error||'Não foi possível salvar.');return}onSaved()}return <div className="sheet" onMouseDown={e=>{if(e.currentTarget===e.target)onClose()}}><div className="sheetPanel"><div className="sheetHandle"/><h2>{item?'Editar profissional':'Novo profissional'}</h2>{error&&<div className="inlineError">{error}</div>}<div className="formGrid"><div className="formField"><label>Nome</label><input value={name} onChange={e=>setName(e.target.value)}/></div><div className="formField"><label>Telefone</label><input inputMode="tel" value={phone} onChange={e=>setPhone(e.target.value)}/></div><div className="formField"><label>Serviços que atende</label><div className="choiceGrid">{services.map(s=><label key={s.id} className={enabled.includes(s.id)?'choiceCard selected':'choiceCard'}><input type="checkbox" checked={enabled.includes(s.id)} onChange={e=>setEnabled(v=>e.target.checked?[...v,s.id]:v.filter(x=>x!==s.id))}/> {s.name}</label>)}</div></div><button className="touchButton primary" onClick={save}>Salvar</button></div></div></div>}
