package com.troquim_bot.conversation.state;

public enum ConversationStep {
    INICIO,
    AGUARDANDO_SERVICO,
    AGUARDANDO_DIA,
    AGUARDANDO_HORARIO,
    AGUARDANDO_ESCOLHA_NOME,
    AGUARDANDO_NOME,
    AGUARDANDO_CONFIRMACAO,
    AGUARDANDO_CANCELAMENTO,
    FINALIZADO
}
