-- =====================================================================
-- V1 — Baseline do schema existente (PostgreSQL).
--
-- Reproduz o schema que hoje é gerado pelo Hibernate (ddl-auto) para os
-- 4 agregados persistidos: customers, appointments, reservations,
-- conversation_states. A partir daqui o Flyway é a autoridade do schema
-- no PostgreSQL e o Hibernate apenas valida.
--
-- Customer AINDA sem business_id/phone_e164 aqui — a tenancy entra em V2.
-- =====================================================================

CREATE TABLE customers (
    id                  UUID         NOT NULL,
    first_name          VARCHAR(100) NOT NULL,
    last_name           VARCHAR(100) NOT NULL,
    phone               VARCHAR(20)  NOT NULL,
    apelido             VARCHAR(50),
    notes               VARCHAR(500),
    status              VARCHAR(20)  NOT NULL,
    total_atendimentos  INTEGER      NOT NULL,
    ultimo_atendimento  TIMESTAMP,
    criado_em           TIMESTAMP    NOT NULL,
    atualizado_em       TIMESTAMP    NOT NULL,
    CONSTRAINT pk_customers PRIMARY KEY (id)
);

CREATE TABLE appointments (
    id                UUID        NOT NULL,
    customer_id       UUID        NOT NULL,
    professional_id   UUID        NOT NULL,
    service_id        UUID        NOT NULL,
    availability_id   UUID        NOT NULL,
    reservation_id    UUID,
    date              DATE        NOT NULL,
    start_time        TIME        NOT NULL,
    end_time          TIME        NOT NULL,
    status            VARCHAR(20) NOT NULL,
    criado_em         TIMESTAMP   NOT NULL,
    atualizado_em     TIMESTAMP   NOT NULL,
    CONSTRAINT pk_appointments PRIMARY KEY (id)
);

CREATE TABLE reservations (
    id                UUID        NOT NULL,
    customer_id       UUID        NOT NULL,
    professional_id   UUID        NOT NULL,
    service_id        UUID        NOT NULL,
    availability_id   UUID        NOT NULL,
    date              DATE        NOT NULL,
    start_time        TIME        NOT NULL,
    end_time          TIME        NOT NULL,
    expires_at        TIMESTAMP   NOT NULL,
    status            VARCHAR(20) NOT NULL,
    criado_em         TIMESTAMP   NOT NULL,
    atualizado_em     TIMESTAMP   NOT NULL,
    CONSTRAINT pk_reservations PRIMARY KEY (id)
);

CREATE TABLE conversation_states (
    numero         VARCHAR(50) NOT NULL,
    state_json     TEXT        NOT NULL,
    criado_em      TIMESTAMP   NOT NULL,
    atualizado_em  TIMESTAMP   NOT NULL,
    CONSTRAINT pk_conversation_states PRIMARY KEY (numero)
);

-- Entidades legadas (model.Cliente / model.OrdemServico) usadas por
-- ClienteController/OrdemServicoController. Fora do escopo desta tarefa, mas
-- precisam existir no baseline porque o Hibernate valida TODAS as entidades.
CREATE TABLE clientes (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome         VARCHAR(255) NOT NULL,
    telefone     VARCHAR(255),
    email        VARCHAR(255),
    observacao   TEXT,
    CONSTRAINT pk_clientes PRIMARY KEY (id),
    CONSTRAINT uq_clientes_email UNIQUE (email)
);

CREATE TABLE ordens_servico (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    cliente_id        BIGINT       NOT NULL,
    aparelho          VARCHAR(255) NOT NULL,
    defeito_relatado  TEXT,
    status            VARCHAR(255) NOT NULL,
    valor_estimado    NUMERIC(38,2),
    data_criacao      TIMESTAMP    NOT NULL,
    CONSTRAINT pk_ordens_servico PRIMARY KEY (id),
    CONSTRAINT fk_ordens_servico_cliente FOREIGN KEY (cliente_id) REFERENCES clientes (id)
);
